name: unix
description: A simple get unix timestamp exec. Only support cli. 
version: 1.0.0
homepage: https://github.com/CaiJingLong/dart-unix-exec
author: Caijinglong <cjl_spy@163.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0

executables:
  unix: 